/**
 * Metadata for a single blog post, as generated by
 * scripts/build-posts-index.js into public/posts/index.json.
 *
 * Only lightweight metadata lives here — the full Markdown body is fetched
 * separately (per post) when a post is opened.
 */
export interface PostMeta {
  slug: string;
  title: string;
  date: string; // ISO date, e.g. "2026-06-22"
  tags: string[];
  excerpt: string;
  thumbnail: string | null;
  readingTime: number; // minutes
}

export interface PostIndex {
  generatedAt: string;
  count: number;
  posts: PostMeta[];
}

export type SortKey = 'date-desc' | 'date-asc' | 'title-asc';
